const {
  PUBLIC_BASE_URL_CLIENT,
  PUBLIC_BASE_URL_SERVER,
  PUBLIC_ENV,
  PUBLIC_PORT_NUMBER_CLIENT,
  PUBLIC_PORT_NUMBER_SERVER,
} = import.meta.env;

export const baseUrlClient = PUBLIC_ENV === 'development' ? `${PUBLIC_BASE_URL_CLIENT}:${PUBLIC_PORT_NUMBER_CLIENT}` : PUBLIC_BASE_URL_CLIENT;
export const baseUrlServer = PUBLIC_ENV === 'development' ? `${PUBLIC_BASE_URL_SERVER}:${PUBLIC_PORT_NUMBER_SERVER}` : PUBLIC_BASE_URL_SERVER;
