const SERVICE_MODE_AEROPLANE = 'aeroplane';
const SERVICE_MODE_AIRPORT_CONNECTION = 'airport-connection';
const SERVICE_MODE_BUS = 'bus';
const SERVICE_MODE_COACH = 'coach';
const SERVICE_MODE_DLR = 'dlr';
const SERVICE_MODE_ELIZABETH_LINE = 'elizabeth-line';
const SERVICE_MODE_EUROSTAR = 'eurostar';
const SERVICE_MODE_NATIONAL_RAIL = 'national-rail';
const SERVICE_MODE_OVERGROUND = 'overground';
const SERVICE_MODE_RIVER_BUS = 'river-bus';
const SERVICE_MODE_TRAM = 'tram';
const SERVICE_MODE_TUBE = 'tube';

export {
  SERVICE_MODE_AEROPLANE,
  SERVICE_MODE_AIRPORT_CONNECTION,
  SERVICE_MODE_BUS,
  SERVICE_MODE_COACH,
  SERVICE_MODE_DLR,
  SERVICE_MODE_ELIZABETH_LINE,
  SERVICE_MODE_EUROSTAR,
  SERVICE_MODE_NATIONAL_RAIL,
  SERVICE_MODE_OVERGROUND,
  SERVICE_MODE_RIVER_BUS,
  SERVICE_MODE_TRAM,
  SERVICE_MODE_TUBE,
};
