const SERVICE_NAME_AEROPLANE = 'Airport';
const SERVICE_NAME_BUS = 'Bus';
const SERVICE_NAME_COACH = 'Coach';
const SERVICE_NAME_CORE = 'Core';
const SERVICE_NAME_EUROSTAR = 'Eurostar';
const SERVICE_NAME_NATIONAL_RAIL = 'National Rail';
const SERVICE_NAME_RIVER_BUS = 'River Bus';

export {
  SERVICE_NAME_AEROPLANE,
  SERVICE_NAME_BUS,
  SERVICE_NAME_COACH,
  SERVICE_NAME_CORE,
  SERVICE_NAME_EUROSTAR,
  SERVICE_NAME_NATIONAL_RAIL,
  SERVICE_NAME_RIVER_BUS,
};
