const SERVICE_NAME_BUS = 'Bus';
const SERVICE_NAME_CORE = 'Core';
const SERVICE_NAME_NATIONAL_RAIL = 'National Rail';
const SERVICE_NAME_RIVER_BUS = 'River Bus';

export {
  SERVICE_NAME_BUS,
  SERVICE_NAME_CORE,
  SERVICE_NAME_NATIONAL_RAIL,
  SERVICE_NAME_RIVER_BUS,
};
