const SERVICE_MODE_BUS = 'bus';
const SERVICE_MODE_DLR = 'dlr';
const SERVICE_MODE_ELIZABETH_LINE = 'elizabeth-line';
const SERVICE_MODE_NATIONAL_RAIL = 'national-rail';
const SERVICE_MODE_OVERGROUND = 'overground';
const SERVICE_MODE_TRAM = 'tram';
const SERVICE_MODE_TUBE = 'tube';

const serviceModes = [
  SERVICE_MODE_BUS,
  SERVICE_MODE_DLR,
  SERVICE_MODE_ELIZABETH_LINE,
  SERVICE_MODE_NATIONAL_RAIL,
  SERVICE_MODE_OVERGROUND,
  SERVICE_MODE_TRAM,
  SERVICE_MODE_TUBE,
];

export {
  SERVICE_MODE_BUS,
  SERVICE_MODE_DLR,
  SERVICE_MODE_ELIZABETH_LINE,
  SERVICE_MODE_NATIONAL_RAIL,
  SERVICE_MODE_OVERGROUND,
  SERVICE_MODE_TRAM,
  SERVICE_MODE_TUBE,
};

export default serviceModes;
